name: push-to-translation-manager
description: This is an action to push to translation manager
author: Pixl8 Group
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  TRANSLATIONS_ENDPOINT:
    description: "Translations API endpoint"
    required: false
    default: "https://translations.pixl8.cloud/api/translations/v1"
  TRANSLATIONS_API_KEY:
    description: "API key for translations service"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'